# Generated by Django 2.1.7 on 2019-03-20 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Slots', '0002_auto_20190320_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointofinterest',
            old_name='name',
            new_name='area_name',
        ),
    ]
